env:
 - GHCVER=7.0.4
 - GHCVER=7.2.2
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq
 - sudo apt-get install -qq cabal-install-1.18 ghc-$GHCVER
 - export PATH="/opt/ghc/$GHCVER/bin:$PATH"

install:
 - cabal-1.18 update
 - ghc --version
 - ghc-pkg list

script:
 - cabal-1.18 install --verbose=2 --enable-documentation
# It is a pity that -O2 causes a warning...
# - cabal-1.18 check --verbose=2
 - cabal-1.18 sdist --verbose=2
